SistemaWebEmpleado/Models/Empleado.cs
using System.ComponentModel.DataAnnotations;
using SistemaWebEmpleado.Validations;

namespace SistemaWebEmpleado.Models
{
    public class Empleado
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Nombre { get; set; }

        [Required]
        public string Apellido { get; set; }

        [Required]
        public string DNI { get; set; }

        [Required]
        [LegajoValidation]
        public string Legajo { get; set; }

        [Required]
        public string Titulo { get; set; }
    }
}

SistemaWebEmpleado/Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaWebEmpleado.Data;
using SistemaWebEmpleado.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SistemaWebEmpleado.Controllers
{
    public class EmpleadoController : Controller
    {
        private readonly EmpleadoContext _context;

        public EmpleadoController(EmpleadoContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            return View(_context.Empleados.ToList());
        }

        [HttpGet]
        [ActionName("Details")]
        public IActionResult Details(int id)
        {
            Empleado empleado = _context.Empleados.Find(id);

            if (empleado == null)
            {
                return NotFound();
            }


            return View("Details", empleado);
        }


        [HttpGet]
        [ActionName("ListarPorTitulo")]
        public IActionResult ListarPorTitulo(string titulo)
        {
            List<Empleado> lista = (from e in _context.Empleados
                                    where e.Titulo == titulo
                                    select e).ToList();
            return View("Index", lista);
        }

        public IActionResult Create()
        {
            Empleado empleado = new Empleado();
            return View("Create", empleado);
        }

        // POST: /Person/Create
        [HttpPost]
        public IActionResult Create(Empleado empleado)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", empleado);
            }
            else
            {
                _context.Empleados.Add(empleado);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public IActionResult Edit(int id)
        {
            Empleado empleado = _context.Empleados.Find(id);
            if (empleado == null)
            {
                return NotFound();
            }
            return View("Edit", empleado);

        }

        [HttpPost]
        public IActionResult Edit(Empleado empleado)
        {

            _context.Entry(empleado).State = EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var person = _context.Empleados.SingleOrDefault(m => m.Id == id);
            _context.Empleados.Remove(person);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

SistemaWebEmpleado/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace SistemaWebEmpleado.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Fecha = DateTime.Now.ToString();
            return View();
        }
    }
}

SistemaWebEmpleado/Views/Empleado/Create.cshtml
@model SistemaWebEmpleado.Models.Empleado
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section sidebar {
    Administracion de Empleados
}

<h4>New Empleado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DNI" class="control-label"></label>
                <input asp-for="DNI" class="form-control" />
                <span asp-validation-for="DNI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Legajo" class="control-label"></label>
                <input asp-for="Legajo" class="form-control" />
                <span asp-validation-for="Legajo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SistemaWebEmpleado/Views/Empleado/Details.cshtml
@model SistemaWebEmpleado.Models.Empleado
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section sidebar {
    Administracion de Empleados
}
    <fieldset>
        <legend><b>Detalle Auto</b></legend>
        <div>
            <b>@Html.DisplayNameFor(model => model.Nombre)</b>
        </div>
        <div>
            @Html.DisplayFor(model => model.Nombre)
        </div>

        <div>
            <b>@Html.DisplayNameFor(model => model.Apellido)</b>
        </div>
        <div>
            @Html.DisplayFor(model => model.Apellido)
        </div>

        <div>
            <b>@Html.DisplayNameFor(model => model.DNI)</b>
        </div>
        <div>
            @Html.DisplayFor(model => model.DNI)
        </div>
        <div>
            <b> @Html.DisplayNameFor(model => model.Legajo)</b>
        </div>
        <div>
            @Html.DisplayFor(model => model.Legajo)
        </div>
        <div>
            <b> @Html.DisplayNameFor(model => model.Titulo)</b>
        </div>
        <div>
            @Html.DisplayFor(model => model.Titulo)
        </div>

    </fieldset>
    <p>
        @Html.ActionLink("Back to list", "Index", "Empleado")
    </p>

SistemaWebEmpleado/Views/Empleado/Edit.cshtml
@model SistemaWebEmpleado.Models.Empleado
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section sidebar {
    Administracion de Empleados
}
    <h2>Editar datos</h2>
@using (Html.BeginForm("Edit", "Empleado", FormMethod.Post))
{
    <p>
        Aula @Html.DisplayFor(model => model.Id):
    </p>

    <p>
        @Html.LabelFor(model => model.Nombre)
        @Html.EditorFor(model => model.Nombre)
        @Html.ValidationMessageFor(model => model.Nombre)
    </p>
    <p>
        @Html.LabelFor(model => model.Apellido)
        @Html.EditorFor(model => model.Apellido)
        @Html.ValidationMessageFor(model => model.Apellido)
    </p>
    <p>
        @Html.LabelFor(model => model.DNI)
        @Html.EditorFor(model => model.DNI)
        @Html.ValidationMessageFor(model => model.DNI)
    </p>
    <p>
        @Html.LabelFor(model => model.Legajo)
        @Html.EditorFor(model => model.Legajo)
        @Html.ValidationMessageFor(model => model.Legajo)
    </p>
            <p>
        @Html.LabelFor(model => model.Titulo)
        @Html.EditorFor(model => model.Titulo)
        @Html.ValidationMessageFor(model => model.Titulo)
        </p>
    <input type="submit" value="Guardar cambios" />
    @Html.ActionLink("Go to index", "Index")
}

SistemaWebEmpleado/Views/Empleado/Index.cshtml
@model IEnumerable<SistemaWebEmpleado.Models.Empleado>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section sidebar {
    Administracion de Empleados
}


<p>@Html.ActionLink("New Empleado", "Create", "Empleado")</p>
<table>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DNI)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Legajo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DNI)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Legajo)
                </td>
                <td>
                    @Html.ActionLink(item.Titulo, "ListarPorTitulo", new { titulo = item.Titulo })
                </td>
                <td>
                    @Html.ActionLink("Detalles", "Details", new { id = item.Id })
                </td>
                <td>
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.Id })
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.Id })
                </td>

            </tr>
        }
    </tbody>
</table>

SistemaWebEmpleado/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@section sidebar {
    Bienvendio estas en la pagina principal.
}

<h3>Fecha @ViewBag.Fecha</h3>
<h2>Bienvenidos a El Rey Can!</h2>
@Html.ActionLink("Ir a empleados", "Index", "Empleado")

SistemaWebEmpleado/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <div id="header">
        <h1>SISTEMA Empleado</h1>
    </div>
    <div id="sidebar">
        @if (IsSectionDefined("sidebar"))
        {
            @RenderSection("sidebar")
        }
        else
        {
            <h2>Zona Sidebar</h2>
        }

    </div>
    <div id="nav">
        @Html.ActionLink("Home", "Index", "Home")
        @Html.ActionLink("Empleado", "Index", "Empleado")
    </div>
    <div id="content">
        @RenderBody()
    </div>
    <div id="footer">
        <h3>Info@Empleado.com</h3>
    </div>
</body>
</html>